apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-driver-validation
  name: nvidia-driver-validation
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  restartPolicy: OnFailure
  containers:
    - name: tensorflow-test
      image: gcr.io/tensorflow/tensorflow:latest-gpu
      imagePullPolicy: Always
      command: ["python"]
      args: ["-u", "-c", "import tensorflow"]
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=5.0"
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
  nodeSelector:
    feature.node.kubernetes.io/pci-10de.present: "true"
